// <auto-generated>
// Code generated by LUISGen BotBanca.json -cs Luis.ClassToGenerate -o 
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.AI.Luis;
namespace Luis
{
    public partial class ClassToGenerate: IRecognizerConvert
    {
        [JsonProperty("text")]
        public string Text;

        [JsonProperty("alteredText")]
        public string AlteredText;

        public enum Intent {
            ActivacionTDC, 
            AfiliacionPagoMovil, 
            afirmacion, 
            AgenciasMetroOeste, 
            AppConexionDigital, 
            AumentoLimiteTDC, 
            BloqueadoSuspendido, 
            BloquearDesbloquearTarjeta, 
            CartaSerial, 
            ClienteNuevo, 
            ComoPagoTDC, 
            conexionBancaribe, 
            ConsultaSaldo, 
            ConsultaSaldoTDC, 
            Contacto, 
            Despedida, 
            EmojisTwitter, 
            GestionEnLinea,
            InfoPtoVenta,
            MontosMaximos, 
            negación, 
            None, 
            NoVeTDC, 
            OlvidoClave, 
            Opciones, 
            PagoMovilSMS, 
            Pensionado, 
            PerfilSeguridad, 
            PreAperturaCta, 
            Reclamo, 
            ReclamoCajero, 
            reclamoNoAbonado, 
            ReclamoPagoMovil, 
            ReclamoPOS, 
            ReclamoRecarga, 
            ReclamoTDC, 
            ReclamoTransferencia, 
            redes, 
            RenovacionTarjeta, 
            Saludar, 
            ServiciosMontoLimite, 
            Tarifa, 
            TarjetaConexionSegura, 
            Tasas, 
            TDCSaldoCero, 
            TiempoPagoTDC, 
            TiempoTransferencia, 
            TipoPersona, 
            TipoTarjeta, 
            transferencia
        };
        [JsonProperty("intents")]
        public Dictionary<Intent, IntentScore> Intents;

        public class _Entities
        {
            // Simple entities
            public string[] Afiliacion;

            public string[] Bs;

            public string[] Clavedinamica;

            public string[] ErrorPos;

            public string[] Extravio;

            public string[] Joven;

            public string[] NoVeo;

            public string[] Olvido;

            public string[] OnlineBanking;

            public string[] QueEs;

            public string[] Robo;

            public string[] SuspendeElimina;

            public string[] TipoCta;

            public string[] año;

            public string[] bancaribedigital;

            public string[] cajero;

            public string[] cambio;

            public string[] comision;

            public string[] comoestas;

            public string[] consulta;

            public string[] despedidainformal;

            public string[] deuda;

            public string[] disponible;

            public string[] divisa;

            public string[] domiciliacion;

            public string[] empleado;

            public string[] equivocado;

            public string[] escribirsms;

            public string[] fiestas;

            public string[] hola;

            public string[] maltrato;

            public string[] maximo;

            public string[] mipagobancaribe;

            public string[] navidad;

            public string[] noabonado;

            public string[] nosvemos;

            public string[] notengo;

            public string[] operar;

            public string[] pagorapido;

            public string[] pensionado;

            public string[] porque;

            public string[] pos;

            public string[] quepaso;

            public string[] quetalestas;

            public string[] quetalteva;

            public string[] reclamo;

            public string[] restaurar;

            public string[] saludoinformal;

            public string[] saludojuvenil;

            public string[] sms;

            public string[] tarjeta;

            public string[] tasa;

            public string[] tiempo;

            public string[] tlfbasico;

            public string[] transferir;

            // Lists
            public string[][] Agencias;

            public string[][] Bloqueado;

            public string[][] Bloqueo;

            public string[][] Carta;

            public string[][] CartaFiniquito;

            public string[][] Desbloqueo;

            public string[][] Extranjero;

            public string[][] NoRecibo;

            public string[][] SaldoCero;

            public string[][] Smartphone;

            public string[][] TeVeo;

            public string[][] TipoCtaBienEscrito;

            public string[][] activar;

            public string[][] ahorroMalEscrito;

            public string[][] apurado;

            public string[][] buenasnoches;

            public string[][] buenatarde;

            public string[][] buendia;

            public string[][] cercana;

            public string[][] clave;

            public string[][] correo;

            public string[][] corrienteMalEscrito;

            public string[][] cuidate;

            public string[][] datos;

            public string[][] gracias;

            public string[][] hablamos;

            public string[][] juridico;

            public string[][] natural;

            public string[][] nopuedo;

            public string[][] nuevo;

            public string[][] numero;

            public string[][] opcion1List;

            public string[][] opcion2List;

            public string[][] opcion3List;

            public string[][] opcion4List;

            public string[][] opcionultimaList;

            public string[][] pasaporte;

            public string[][] perfil;

            public string[][] problema;

            public string[][] rifgobierno;

            public string[][] saber;

            public string[][] solicitud;

            public string[][] suspendido;

            public string[][] tarjetasegura;

            public string[][] tdc;

            public string[][] tdd;

            public string[][] temporal;

            public string[][] usuario;

            public string[][] vencida;

            public string[][] venezolano;

            // Regex entities
            public string[] NroReclamo;

            // Instance
            public class _Instance
            {
                public InstanceData[] Afiliacion;
                public InstanceData[] Agencias;
                public InstanceData[] Bloqueado;
                public InstanceData[] Bloqueo;
                public InstanceData[] Bs;
                public InstanceData[] Carta;
                public InstanceData[] CartaFiniquito;
                public InstanceData[] Clavedinamica;
                public InstanceData[] Desbloqueo;
                public InstanceData[] ErrorPos;
                public InstanceData[] Extranjero;
                public InstanceData[] Extravio;
                public InstanceData[] Joven;
                public InstanceData[] NoRecibo;
                public InstanceData[] NoVeo;
                public InstanceData[] NroReclamo;
                public InstanceData[] Olvido;
                public InstanceData[] OnlineBanking;
                public InstanceData[] QueEs;
                public InstanceData[] Robo;
                public InstanceData[] SaldoCero;
                public InstanceData[] Smartphone;
                public InstanceData[] SuspendeElimina;
                public InstanceData[] TeVeo;
                public InstanceData[] TipoCta;
                public InstanceData[] TipoCtaBienEscrito;
                public InstanceData[] activar;
                public InstanceData[] ahorroMalEscrito;
                public InstanceData[] apurado;
                public InstanceData[] año;
                public InstanceData[] bancaribedigital;
                public InstanceData[] buenasnoches;
                public InstanceData[] buenatarde;
                public InstanceData[] buendia;
                public InstanceData[] cajero;
                public InstanceData[] cambio;
                public InstanceData[] cercana;
                public InstanceData[] clave;
                public InstanceData[] comision;
                public InstanceData[] comoestas;
                public InstanceData[] consulta;
                public InstanceData[] correo;
                public InstanceData[] corrienteMalEscrito;
                public InstanceData[] cuidate;
                public InstanceData[] datos;
                public InstanceData[] despedidainformal;
                public InstanceData[] deuda;
                public InstanceData[] disponible;
                public InstanceData[] divisa;
                public InstanceData[] domiciliacion;
                public InstanceData[] empleado;
                public InstanceData[] equivocado;
                public InstanceData[] escribirsms;
                public InstanceData[] fiestas;
                public InstanceData[] gracias;
                public InstanceData[] hablamos;
                public InstanceData[] hola;
                public InstanceData[] juridico;
                public InstanceData[] maltrato;
                public InstanceData[] maximo;
                public InstanceData[] mipagobancaribe;
                public InstanceData[] natural;
                public InstanceData[] navidad;
                public InstanceData[] noabonado;
                public InstanceData[] nopuedo;
                public InstanceData[] nosvemos;
                public InstanceData[] notengo;
                public InstanceData[] nuevo;
                public InstanceData[] numero;
                public InstanceData[] opcion1List;
                public InstanceData[] opcion2List;
                public InstanceData[] opcion3List;
                public InstanceData[] opcion4List;
                public InstanceData[] opcionultimaList;
                public InstanceData[] operar;
                public InstanceData[] pagorapido;
                public InstanceData[] pasaporte;
                public InstanceData[] pensionado;
                public InstanceData[] perfil;
                public InstanceData[] porque;
                public InstanceData[] pos;
                public InstanceData[] problema;
                public InstanceData[] quepaso;
                public InstanceData[] quetalestas;
                public InstanceData[] quetalteva;
                public InstanceData[] reclamo;
                public InstanceData[] restaurar;
                public InstanceData[] rifgobierno;
                public InstanceData[] saber;
                public InstanceData[] saludoinformal;
                public InstanceData[] saludojuvenil;
                public InstanceData[] sms;
                public InstanceData[] solicitud;
                public InstanceData[] suspendido;
                public InstanceData[] tarjeta;
                public InstanceData[] tarjetasegura;
                public InstanceData[] tasa;
                public InstanceData[] tdc;
                public InstanceData[] tdd;
                public InstanceData[] temporal;
                public InstanceData[] tiempo;
                public InstanceData[] tlfbasico;
                public InstanceData[] transferir;
                public InstanceData[] usuario;
                public InstanceData[] vencida;
                public InstanceData[] venezolano;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        [JsonProperty("entities")]
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<ClassToGenerate>(JsonConvert.SerializeObject(result, new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore }));
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score.Value;
                }
            }
            return (maxIntent, max);
        }
    }
}
